### ISSUE TITLE
Path Parameter name change shows 1 api added and 1 api deleted 

### ISSUE THREAD

**Issue by adarshsharma** [quen2404/openapi-diff#21]
If the name of the path parameter is changed, it shows api removed and a new api added. Should not show any diff

**e.g.** 
old: https://gist.github.com/adarshsharma/0a7d90019afb9fa4591e8e8b285bfe9b
new: https://gist.github.com/adarshsharma/52223a93146316e7b7165090f92a6265

**Comment by quen2404** [comment]
Hi Adarsh, 
i almost fixed this issue, but i have to make a choice between two case: 
1. Should we say that the operation has changed but is backward incompatible (because the path parameter name has changed)
2. should we say that operation didn't change ? 

Because that kind of change could break the api implementation (but i'm agree with you, in theory, the API signature doesn't changed)

**Comment by adarshsharma** [comment]
I think we should say that operation did not change. Because the api call
to server will still work.

**Comment by adarshsharma** [comment]
And since the operation did not change, it'll remain backward compatible.

**Comment by quen2404** [comment]
Yes, i'm working on it. I made the part about the path comparison. Now i have to write the part about the name changement for path parameters. I hope i will push that today.

**Comment by adarshsharma** [comment]
sure. :)
